version: "3"

services:
  cytech-lib-ui:
    container_name: team-b-expense-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - ui_net

networks:
  ui_net:
    driver: bridge
